version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"  # Port pour le débogage à distance
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./:/app:delegated
      - ~/.m2:/home/appuser/.m2:delegated
    user: appuser
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge